### ISSUE TITLE
Module's options "failOnWarning" and "failOnError" don't work

### ISSUE THREAD

**Issue by buravlev-arthur** [nuxt-modules/stylelint#105]
Changing of [failOnWarning](https://github.com/nuxt-modules/stylelint#failonwarning) and [failOnError](https://github.com/nuxt-modules/stylelint#failonerror) boolean options doesn't present any affect. Because of permanent default true state of the "failOnError" option build fails everytime when there is at least one stylelint's error.

I've noticed [vite-plugin-stylelint](https://www.npmjs.com/package/vite-plugin-stylelint?activeTab=readme#options) doesn't have these options in its documentation. I guess it can be reason of this issue.

**Comment by ricardogobbosouza** [comment]
Hi @buravlev-arthur 
These options then exist when using `@nuxt/webpack-builder`
https://nuxt.com/docs/api/nuxt-config#builder

**Comment by buravlev-arthur** [comment]
@ricardogobbosouza, firstly, thank you for your answer!
Now I see. I would propose to text under appropriate options, something like: “Works only along with @nuxt/webpack-builder”. Furthermore, @nuxt/vite-builder is used as default in Nuxt configuration.

**Comment by ricardogobbosouza** [comment]
Yes...need to update documentation
