### ISSUE TITLE
Deprecation warnings in the dev console output

### ISSUE THREAD

**Issue by karol-bujacek** [nuxt-modules/stylelint#118]
The latest released version, 5.1.0, contains vite-plugin-stylelint version 4.3.0, which is not compatible with stylelint version 16. See https://github.com/ModyQyW/vite-plugin-stylelint/issues/56

Dependencies of this module in the branch main are updated, but a new version has not been released. Please release a new version with updated dependencies.

**Comment by karol-bujacek** [comment]
Note: stylelint-webpack-plugin 5.0.0 is required too (https://github.com/webpack-contrib/stylelint-webpack-plugin/releases/tag/v5.0.0)

**Comment by ricardogobbosouza** [comment]
Released https://github.com/nuxt-modules/stylelint/releases/tag/v5.2.0
